class CheckoutBasicLocators:
    ICON_SEARCH_MOBILE = "//div[@class='p-2']//*[name()='svg' and @class='cursor-pointer']"
    LOGO_YODY = "//div[@class='flex flex-grow justify-center']"
    INPUT_SEARCH_DESKTOP = "//input[@class=' input__l input--default pl-12 pr-12  w-full bg-yd-grey-light-2 hover:bg-yd-grey-light-3 rounded-[1.25rem] text-yd-body-2 focus:border-0  !rounded-[1.25rem] bg-[#F2F5F8] w-full md:h-12 truncate']"
    TEXT_SEARCH = 'T-shirt Kid Bé'
    ITEM_PRODUCT_FIRST_ELEMENT = "//div[@class='font-medium text-yd-label-3 xlg:text-[14px] text-yd-typo-title line-clamp-1 min-h-[22px] xlg:min-h-[24px] !font-[400] capitalize']"
    BUTTON_UPDATE_QUALITY_PLUS = "//button[@class='product-quantity-update-tool_button__dMhNl product-quantity-update-tool_button_right__MHn0c product-quantity-update-tool_button-normal__YS_yD  undefined']"
    BUTTON_ADD_CART = "//button[contains(@class, 'product-call-to-action_add-cart_button') and .//span[text()='Thêm vào giỏ']]"
    ICON_REMOVE_POPUP = "//div[@class='flex items-center']//*[name()='svg' and @class='ml-auto rotate-45 cursor-pointer']"
    BUTTON_BUY_NOW = "//button[contains(@class, 'btn-extra-large') and contains(@class, 'product-call-to-action_buy-now_button') and .//span[text()='Mua ngay']]"
    BUTTON_CLEAR_TEXT = "//button[@class='hover:scale-110 active:scale-100 inline-block focus-visible:outline-none visited:outline-none opacity-60 group-hover:opacity-100 transition-all duration-200 hover:duration-75 undefined']"
    TEXT_SEARCH_2ND = 'ao polo'
    BUTTON_UPDATE_PRODUCT = "//button[@class=' btn btn-small md:btn-medium btn-solid-default bg-yd-grey-light-2 text-yd-button-text-5 xlg:text-yd-button-text-3 w-fit text-yd-typo-title disabled:bg-yd-grey-light-2 disabled:!text-yd-typo-disabled rounded-lg ']"
    BUTTON_UPDATE_POPUP = "//div[@class='py-3 xmd:py-0']//div[@class='font-semibold text-yd-button-text-1 text-yd-typo-title']"
    BUTTON_UPDATE_PRODUCT_2 = "(//button[@class=' btn btn-small md:btn-medium btn-solid-default bg-yd-grey-light-2 text-yd-button-text-5 xlg:text-yd-button-text-3 w-fit text-yd-typo-title disabled:bg-yd-grey-light-2 disabled:!text-yd-typo-disabled rounded-lg '])[2]"
    QUALITY_PLUS_POPUP = "(//button[@class= 'product-quantity-update-tool_button__dMhNl product-quantity-update-tool_button_right__MHn0c product-quantity-update-tool_button-normal__YS_yD product-quantity-update-tool_small__RSqR_']//*[name()='svg' and @class='product-quantity-update-tool_icon__7wU6c'])[2]"
    QUALITY_MINUS_POPUP = "(//button[@class= 'product-quantity-update-tool_button__dMhNl product-quantity-update-tool_button_right__MHn0c product-quantity-update-tool_button-normal__YS_yD product-quantity-update-tool_small__RSqR_']//*[name()='svg' and @class='product-quantity-update-tool_icon__7wU6c'])"
    BUTTON_CHECKOUT = "//button[@class=' btn btn-extra-large btn-solid btn-solid-primary btn-solid-3d-primary w-full mt-7']"
    BUTTON_INPUT_SEARCH_DESKTOP = "//input[@class=' input__m input--default pl-12 pr-4  bg-yd-grey-light-2 hover:bg-yd-grey-light-3 focus:bg-yd-grey-light-3 text-yd-body-2 transition-all duration-200 w-[10.5rem] !rounded-[1.25rem] truncate']"
    TEXT_LINK_ELEMENT = "//span[@class='font-regular md:font-regular text-yd-subtitle-3 md:text-yd-subtitle-2 text-yd-typo-subtitle group-hover:text-yd-alert-info ']"
    FILL_NAME_CUS = "//input[@class=' input__xl input--default pl-12 pr-4  w-full h-[52px] !pr-3 !pl-[42px] rounded-[4px] placeholder:text-yd-gray-100 border-yd-gray-50 truncate'][@name='name']"
    DATA_NAME = "Test Đơn web"
    DATA_PHONE = "0900000001"
    DATA_DETAIL_ADDRESS = "90 Le Loi"
    FILL_NUMBER_CUS = "//input[@class=' input__xl input--default pl-12 pr-4  w-full h-[52px] !pr-3 !pl-[42px] rounded-[4px] placeholder:text-yd-gray-100 border-yd-gray-50 truncate'][@name='phone']"
    ADDRESS_CUS = "//div[@class = 'w-full relative select-city-district-ward !rounded-[4px] !border-yd-gray-50 text-yd-typo-title']"
    ADDRESS_CITY = "//input[@class= ' input__m input--default pl-12 pr-4  w-full w-full h-11 !pl-9 !rounded-none !border-t-0 !border-r-0 !border-l-0 truncate']"
    CHOOSE_CITY = "//div[@class= 'font-regular text-yd-label-4 text-yd-typo-label']"
    ADDRESS_PROVINCE = "//input[@class= ' input__m input--default pl-12 pr-4  w-full w-full h-11 !pl-9 !rounded-none !border-t-0 !border-r-0 !border-l-0 truncate']"
    CHOOSE_PROVINCE = "//div[@class= 'font-regular text-yd-label-4 text-yd-typo-label']"
    DETAIL_ADDRESS = "//input[@name='address'][@class=' input__xl input--default pl-4 pr-4  w-full h-[52px] rounded-[4px] placeholder:text-yd-gray-100 border-yd-gray-50 truncate']"
    NOTE_ORDER = "//input[@class=' input__xl input--default pl-12 pr-4  w-full h-[52px] !pr-3 !pl-[42px] rounded-[4px] placeholder:text-yd-gray-100 border-yd-gray-50 truncate'][@name= 'note']"
    PAYMENT = "//button[@class= ' btn btn-solid btn-solid-primary btn-solid-3d-primary w-full h-[48px]']"
